### ISSUE TITLE
COAP protocol support

### ISSUE THREAD

**Issue by tgerczei** [urbas/philips-air-purifier#1]
My 1000i and 2000i devices default to it. I'd love to use your Prometheus exporter which also relies on this package and would rather not re-invent hot water myself. The message that gets logged during the downstream request issued is as follows:

MY.IP.ADD.RESS - - [08/Nov/2020 07:47:43] "GET /metrics/ HTTP/1.1" 404 -
ERROR:root:Could not read values from Philips Air Purifier AN.IP.ADD.RESS. Error: HTTPConnectionPool(host='AN.IP.ADD.RESS', port=80): Max retries exceeded with url: /di/v1/products/1/air (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x744b8d10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by urbas** [comment]
Hi @tgerczei!

COAP protocol support sounds like a great idea :+1: 

Before we go down this route though, I'd just like to check how sure you are that your device does not support the HTTP protocol?

For example, it might be that your purifier is not connected to your WiFi network.

I now added wifi setup instructions in PR #2. Take a look at the README.md in case you are trying to connect your purifier to your WiFi network.

**Comment by tgerczei** [comment]
Hello @urbas,

Thanks for the swift response and helpful attitude! It's much appreciated - I might not have expressed myself well and I apologize: my purifiers are connected and reachable via COAP and code in [this repository](https://github.com/rgerganov/py-air-control). I would rather not switch them to another protocol (i.e. HTTP) - thereby altering their defaults - unless I had a really good reason to - they're all brand new. This might seem selfish, of course, I'm well aware of that. Metrics exposed to Prometheus aren't vital, but I'd find it interesting to track and since I already use Prometheus for other purposes, it would be very easy to do, if only I had an exporter and I do like yours.

**Comment by urbas** [comment]
Ah, I see. Yes, I'll port the exporter to py-air-control.

I will also deco this repo and direct people to py-air-control. I think this repo is no longer needed since py-air-control now seems to expose a public API.

**Comment by tgerczei** [comment]
This hadn't been my intention - I didn't mean to dishearten you or point out any discrepancies. That said that is a logical direction indeed and I'll be happy to use your exporter, whichever library it ends up being powered by.

**Comment by urbas** [comment]
Not at all, no worries! I'm happy and excited that we can now consolidate and join efforts in a single project. I'm sure this is going to be for the benefit of everyone. :+1: 

Keep an eye open on the exporter, but it might take a little while to get it done. :sweat_smile:

**Comment by tgerczei** [comment]
:+1: :tada: Thank you - I'm hereby volunteering to test whatever development occurs. :)

**Comment by urbas** [comment]
@tgerczei: I now added support for coap to [the exporter](https://github.com/urbas/philips_air_purifier_exporter). Unfortunately, I was not able to test it (I can only test the http protocol).

Could you please give it a try?

Please follow the [README.md](https://github.com/urbas/philips_air_purifier_exporter) instructions. If the instructions don't work for you, please let me know and I'll fix them.

In the (very likely) event that it doesn't work, could you please send over the logs it produces? It should print out useful information that will allow me to fix it.

**Comment by tgerczei** [comment]
On the contrary, it works perfectly. :) You rock! :metal:

**Comment by urbas** [comment]
Hah, awesome! Super glad it works! Happy prometheising! :chart_with_downwards_trend:

**Comment by tgerczei** [comment]
Thanks, I've actually built container images from this and am happily running/scraping them on a Raspberry Pi 3B+ now ;)
